/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
/**
 *
 * @author atishay197
 */
public class ManagerView extends javax.swing.JFrame {

    /**
     * Creates new form ManagerView
     */
    public ManagerView() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)IngidientTable.getModel();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atishaydatabase","","");
            
            String a1 = "";
            Statement st = con.createStatement();
            String sq = "Select sum(profit) from orderlist";
            ResultSet rs1 = st.executeQuery(sq);
            while(rs1.next())
            {
                a1 = rs1.getString("sum(profit)");
            }
            ProfitMadeLabel.setText(a1);
           
            String a3 = "";
            Statement st3 = con.createStatement();
            String sq2 = "Select orderno from orderlist";
            ResultSet rs2 = st3.executeQuery(sq2);
            while(rs2.next())
            {
                a3 = rs2.getString("orderno");
            }
            CurrentOrderNoLabel.setText(a3);
            
            String sql = "Select * from ingridient;";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                String a2 = rs.getString("name");
                int b1 = rs.getInt("qty");
                model.addRow(new Object[]{a2,b1});
            }
            rs.close();
            st.close();
            con.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CurrentOrderLabel = new javax.swing.JLabel();
        CurrentOrderNoLabel = new javax.swing.JLabel();
        ProfitLabel = new javax.swing.JLabel();
        ProfitMadeLabel = new javax.swing.JLabel();
        AddLabel = new javax.swing.JLabel();
        QtyText = new javax.swing.JTextField();
        QtyLabel = new javax.swing.JLabel();
        Ingridientdrop = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        IngidientTable = new javax.swing.JTable();
        Addbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CurrentOrderLabel.setText("Current Order");

        CurrentOrderNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CurrentOrderNoLabel.setText("345");

        ProfitLabel.setText("Profit");

        ProfitMadeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProfitMadeLabel.setText("576");

        AddLabel.setText("Add Ingridient");

        QtyText.setText("0");

        QtyLabel.setText("Quantity");

        Ingridientdrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bread", "Chicken", "Vegetable", "Paneer", "Morroca", "American", "Mexican", "Coke", "Pepsi", "Mirinda", "7up", "Potato", "CI", "BI" }));
        Ingridientdrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngridientdropActionPerformed(evt);
            }
        });

        IngidientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingridient", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(IngidientTable);

        Addbutton.setText("ADD");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ProfitLabel)
                            .addComponent(AddLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ingridientdrop, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(ProfitMadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QtyLabel)
                            .addComponent(CurrentOrderLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CurrentOrderNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfitLabel)
                    .addComponent(ProfitMadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentOrderLabel)
                    .addComponent(CurrentOrderNoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLabel)
                    .addComponent(Ingridientdrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QtyLabel)
                    .addComponent(QtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngridientdropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngridientdropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngridientdropActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        // TODO add your handling code here:
        String x = Ingridientdrop.getSelectedItem().toString();
        String y = QtyText.getText();
        
        
        DefaultTableModel model = (DefaultTableModel)IngidientTable.getModel();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atishaydatabase","","");
            Statement st1 = con.createStatement();
            String sql1 = "update ingridient set qty = qty + " + y + " where name = '" + x + "';";
            st1.executeUpdate(sql1);
            Statement st = con.createStatement();
            model.setRowCount(0);
            DefaultTableModel model1 = (DefaultTableModel)IngidientTable.getModel();
            String sql = "Select * from ingridient;";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                String a1 = rs.getString("name");
                int b1 = rs.getInt("qty");
                model1.addRow(new Object[]{a1,b1});
            }
            rs.close();
            st.close();
            con.close();
            QtyText.setText("0");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in connection" + e);
        }
    }//GEN-LAST:event_AddbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JButton Addbutton;
    private javax.swing.JLabel CurrentOrderLabel;
    private javax.swing.JLabel CurrentOrderNoLabel;
    private javax.swing.JTable IngidientTable;
    private javax.swing.JComboBox Ingridientdrop;
    private javax.swing.JLabel ProfitLabel;
    private javax.swing.JLabel ProfitMadeLabel;
    private javax.swing.JLabel QtyLabel;
    private javax.swing.JTextField QtyText;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
