/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author atishay197
 */
public class OrderFrame extends javax.swing.JFrame {
    
    double total = 0;
    int order = 1;
    int itemcounter = 0;
    int orderplaced = 0;
    int discount = 0;
        String a = "Mc Chicken";
        String b = "McSpicy Chicken";
        String c = "Mc Veggie";
        String d = "Mc Paneer";
        String e = "McSpicy Paneer";
        String f = "Morrocon Burger";
        String g = "American Burger";
        String h = "Mexican Burger";
        String i = "CocaCola";
        String j = "Pepsi";
        String k = "Mirinda";
        String l = "7UP";
        String m = "Large Fries";
        String n = "Chocolate IC";
        String o = "ButterSct IC";
        String p = "Small Fries";
        
        int a1 = 120;
        int b1 = 250;
        int c1 = 100;
        int d1 = 110;
        int e1 = 120;
        int f1 = 200;
        int g1 = 250;
        int h1 = 230;
        int i1 = 50;
        int j1 = 60;
        int k1 = 50;
        int l1 = 40;
        int m1 = 80;
        int n1 = 60;
        int o1 = 60;
        int p1 = 30;
        
        ManagerView manview = new ManagerView();
        CookView cookview = new CookView();
    /**
     * Creates new form OrderFrame
     */
    public void frameopener ()
    {
        manview.show();
        cookview.setLocation(350-cookview.getSize().width/2, 700-this.getSize().height/2);
        cookview.show();
    }
    public void frameopener1 ()
    {
        ManagerView manview1 = new ManagerView();
        CookView cookview1 = new CookView();
        manview1.show();
        cookview1.setLocation(350-cookview.getSize().width/2, 700-this.getSize().height/2);
        cookview1.show();
    }
    public void framecloser ()
    {
        manview.hide();
        manview.dispose();
        cookview.hide();
        cookview.dispose();
    }
    public OrderFrame() {
        initComponents();
        frameopener();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CNameLabel = new javax.swing.JLabel();
        CPhNoLabel = new javax.swing.JLabel();
        CName = new javax.swing.JTextField();
        CPhNo = new javax.swing.JTextField();
        CUID = new javax.swing.JLabel();
        uidLabel = new javax.swing.JLabel();
        MENULabel = new javax.swing.JLabel();
        BurgerLabel = new javax.swing.JLabel();
        DrinkLabel = new javax.swing.JLabel();
        OthersLabel = new javax.swing.JLabel();
        OrderNoLAbel = new javax.swing.JLabel();
        Order = new javax.swing.JLabel();
        sevenUPButton = new javax.swing.JButton();
        PepsiButton = new javax.swing.JButton();
        CocaColaButton = new javax.swing.JButton();
        MirindaButon = new javax.swing.JButton();
        Burger1 = new javax.swing.JButton();
        Burger2 = new javax.swing.JButton();
        Burger4 = new javax.swing.JButton();
        Burger3 = new javax.swing.JButton();
        Burger6 = new javax.swing.JButton();
        Burger5 = new javax.swing.JButton();
        Burger8 = new javax.swing.JButton();
        Burger7 = new javax.swing.JButton();
        ItemList = new java.awt.List();
        FrenchFriesLButton = new javax.swing.JButton();
        CIcecreamButton = new javax.swing.JButton();
        BSIcecreamButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();
        TotalCost = new javax.swing.JLabel();
        PriceList = new java.awt.List();
        cancelButton = new javax.swing.JButton();
        TotalLabela = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        FrenchFriesSButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        DiscountL = new javax.swing.JLabel();
        discountlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalCostLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CNameLabel.setText("Customer Name");

        CPhNoLabel.setText("Customer Ph. No.");

        CPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPhNoActionPerformed(evt);
            }
        });

        CUID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CUID.setText("0");

        uidLabel.setText("Customer unique id");

        MENULabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MENULabel.setText("MENU");

        BurgerLabel.setText("Burger");

        DrinkLabel.setText("Drinks");

        OthersLabel.setText("Others");

        OrderNoLAbel.setText("Order Number");

        Order.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Order.setText("1");

        sevenUPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/7up.jpg"))); // NOI18N
        sevenUPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenUPButtonActionPerformed(evt);
            }
        });

        PepsiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/Pepsi.jpg"))); // NOI18N
        PepsiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepsiButtonActionPerformed(evt);
            }
        });

        CocaColaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/CocaCola.jpg"))); // NOI18N
        CocaColaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CocaColaButtonActionPerformed(evt);
            }
        });

        MirindaButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/Mirinda.jpg"))); // NOI18N
        MirindaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MirindaButonActionPerformed(evt);
            }
        });

        Burger1.setText("McChicken");
        Burger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger1ActionPerformed(evt);
            }
        });

        Burger2.setText("McSpicy Chicken");
        Burger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger2ActionPerformed(evt);
            }
        });

        Burger4.setText("Mc Paneer");
        Burger4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger4ActionPerformed(evt);
            }
        });

        Burger3.setText("Mc Veggie");
        Burger3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger3ActionPerformed(evt);
            }
        });

        Burger6.setText("Morrocon Burger");
        Burger6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger6ActionPerformed(evt);
            }
        });

        Burger5.setText("Mc Spicy Paneer");
        Burger5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger5ActionPerformed(evt);
            }
        });

        Burger8.setText("Mexican Burger");
        Burger8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger8ActionPerformed(evt);
            }
        });

        Burger7.setText("American Burger");
        Burger7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Burger7ActionPerformed(evt);
            }
        });

        ItemList.setMultipleMode(true);
        ItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListActionPerformed(evt);
            }
        });

        FrenchFriesLButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/lf.jpg"))); // NOI18N
        FrenchFriesLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchFriesLButtonActionPerformed(evt);
            }
        });

        CIcecreamButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/ci.jpg"))); // NOI18N
        CIcecreamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIcecreamButtonActionPerformed(evt);
            }
        });

        BSIcecreamButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/bs.jpg"))); // NOI18N
        BSIcecreamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSIcecreamButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        OrderButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderButton.setText("PLACE ORDER");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        TotalCost.setText("0");

        cancelButton.setText("Cancel Order");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        TotalLabela.setText("Sum : ");

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        FrenchFriesSButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DrinkIcon/sf.jpg"))); // NOI18N
        FrenchFriesSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchFriesSButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        DiscountL.setText("Discount");

        discountlabel.setText("0%");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("TOTAL : ");

        TotalCostLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalCostLabel.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(MENULabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OrderNoLAbel)
                .addGap(24, 24, 24)
                .addComponent(Order)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BurgerLabel)
                            .addComponent(CPhNoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CPhNo)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(DrinkLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(uidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CUID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Burger5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OthersLabel)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Burger2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(CocaColaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Burger3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Burger4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(MirindaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sevenUPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PepsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Burger7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Burger8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Burger6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BSIcecreamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrenchFriesSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CIcecreamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrenchFriesLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TotalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TotalLabela)
                                        .addGap(18, 18, 18)
                                        .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DiscountL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(discountlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(PriceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CUID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uidLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CNameLabel)
                                    .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CPhNoLabel)
                                    .addComponent(CPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MENULabel)
                            .addComponent(OrderNoLAbel)
                            .addComponent(Order))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BurgerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DrinkLabel))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Burger1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Burger2))
                            .addComponent(CocaColaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PepsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Burger3)
                                .addGap(6, 6, 6)
                                .addComponent(Burger4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Burger5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Burger6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Burger7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Burger8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sevenUPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MirindaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(OthersLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FrenchFriesLButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FrenchFriesSButton)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CIcecreamButton, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(BSIcecreamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemList, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(PriceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(RemoveButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TotalLabela)
                                    .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DiscountL)
                                    .addComponent(discountlabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cancelButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPhNoActionPerformed

    private void Burger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger1ActionPerformed
        // TODO add your handling code here:
        ItemList.add(a);
        PriceList.add("" + (a1));
        total += a1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger1ActionPerformed

    private void Burger2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger2ActionPerformed
        // TODO add your handling code here:
        ItemList.add(b);
        PriceList.add("" + (b1));
        total += b1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger2ActionPerformed

    private void Burger3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger3ActionPerformed
        // TODO add your handling code here:
        ItemList.add(c);
        PriceList.add("" + (c1));
        total += c1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger3ActionPerformed

    private void Burger4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger4ActionPerformed
        // TODO add your handling code here:
        ItemList.add(d);
        PriceList.add("" + (d1));
        total += d1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger4ActionPerformed

    private void Burger5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger5ActionPerformed
        // TODO add your handling code here:
        ItemList.add(e);
        PriceList.add("" + (e1));
        total += e1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger5ActionPerformed

    private void Burger6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger6ActionPerformed
        // TODO add your handling code here:
        ItemList.add(f);
        PriceList.add("" + (f1));
        total += f1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger6ActionPerformed

    private void Burger7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger7ActionPerformed
        // TODO add your handling code here:
        ItemList.add(g);
        PriceList.add("" + (g1));
        total += g1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger7ActionPerformed

    private void Burger8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Burger8ActionPerformed
        // TODO add your handling code here:
        ItemList.add(h);
        PriceList.add("" + (h1));
        total += h1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_Burger8ActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        int x = ItemList.getSelectedIndex();
        total -= Integer.parseInt(PriceList.getItem(x));
        TotalCost.setText("" + total);
        itemcounter--;
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            double Total1 = total*0.9;
            TotalCostLabel.setText("" + Total1);
        }
        ItemList.remove(x);
        PriceList.remove(x);
        repaint();
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void CocaColaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CocaColaButtonActionPerformed
        // TODO add your handling code here:
        ItemList.add(i);
        PriceList.add("" + (i1));
        total += i1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_CocaColaButtonActionPerformed

    private void PepsiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepsiButtonActionPerformed
        // TODO add your handling code here:
        ItemList.add(j);
        PriceList.add("" + (j1));
        total += j1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_PepsiButtonActionPerformed

    private void MirindaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MirindaButonActionPerformed
        // TODO add your handling code here:
        ItemList.add(k);
        PriceList.add("" + (k1));
        total += k1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_MirindaButonActionPerformed

    private void sevenUPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenUPButtonActionPerformed
        // TODO add your handling code here:
        ItemList.add(l);
        PriceList.add("" + (l1));
        total += l1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_sevenUPButtonActionPerformed

    private void FrenchFriesLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchFriesLButtonActionPerformed
        // TODO add your handling code here:
        ItemList.add(m);
        PriceList.add("" + (m1));
        total += m1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_FrenchFriesLButtonActionPerformed

    private void CIcecreamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIcecreamButtonActionPerformed
        // TODO add your handling code here:
        ItemList.add(n);
        PriceList.add("" + (n1));
        total += n1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_CIcecreamButtonActionPerformed

    private void BSIcecreamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSIcecreamButtonActionPerformed
        // TODO add your handling code here:
        ItemList.add(o);
        PriceList.add("" + (o1));
        total += o1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_BSIcecreamButtonActionPerformed

    private void ItemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
            String[] items = ItemList.getItems();
        for(int i =0 ; i< itemcounter ; i++)
        {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atishaydatabase","","");
                String name = "",vegnon = "";
                int profit = 0;
                String sql = "", sql1 = "",sql2 = "";
                name = items[i];
                Statement st1 = con.createStatement();
                if(name.equals("Mc Chicken"))
                {
                    sql = "insert into orderlist values('"+name+"','n','"+order+"','25');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Chicken';"; 
                }
                if(name.equals("McSpicy Chicken"))
                {
                    sql = "insert into orderlist values('"+name+"','n','"+order+"','30');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Chicken';"; 
                }
                if(name.equals("Mc Veggie"))
                {
                    sql = "insert into orderlist values('"+name+"','v','"+order+"','25');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Vegetable';"; 
                }
                if(name.equals("Mc Paneer"))
                {
                    sql = "insert into orderlist values('"+name+"','v','"+order+"','30');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Paneer';"; 
                }
                if(name.equals("McSpicy Paneer"))
                {
                    sql = "insert into orderlist values('"+name+"','v','"+order+"','35');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Paneer';"; 
                }
                if(name.equals("Morrocon Burger"))
                {
                    sql = "insert into orderlist values('"+name+"','n','"+order+"','40');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Morroca';"; 
                }
                if(name.equals("American Burger"))
                {
                    sql = "insert into orderlist values('"+name+"','v','"+order+"','45');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'American';"; 
                }
                if(name.equals("Mexican Burger"))
                {
                    sql = "insert into orderlist values('"+name+"','n','"+order+"','45');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Bread';"; 
                    sql2 = "update ingridient set qty = qty - 1 where name = 'Mexican';"; 
                }
                if(name.equals("CocaCola"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Coke';"; 
                }
                if(name.equals("Pepsi"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Pepsi';"; 
                }
                if(name.equals("Mirinda"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Mirinda';"; 
                }
                if(name.equals("7UP"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = '7up';"; 
                }
                if(name.equals("Large Fries"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','25');";
                    sql1 = "update ingridient set qty = qty - 2 where name = 'Potato';"; 
                }
                if(name.equals("Small Fries"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'Potato';"; 
                }
                if(name.equals("Chocolate IC"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'CI';"; 
                }
                if(name.equals("ButterSct IC"))
                {
                    sql = "insert into orderlist values('"+name+"','o','"+order+"','20');";
                    sql1 = "update ingridient set qty = qty - 1 where name = 'BI';";  
                }
                st1.executeUpdate(sql);
                st1.executeUpdate(sql1);
                st1.executeUpdate(sql2);
                st1.close();
                con.close();
            }
            catch (Exception e)
            {
                //JOptionPane.showMessageDialog(this, "Error in connection" + e);
            }
        }
        framecloser();
        frameopener1();
        orderplaced = 0;
        discount = 0;
        itemcounter = 0;
        total = 0;
        TotalCost.setText("0");
        TotalCostLabel.setText("0");
        discountlabel.setText("0%");
        order++;
        CName.setText("");
        CPhNo.setText("");
        CUID.setText("ADD!");
        Order.setText("" + order);
        PriceList.removeAll();
        ItemList.removeAll();
        repaint();
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:total = 0;
        total = 0;
        itemcounter = 0;
        TotalCost.setText("0");
        TotalCostLabel.setText("0");
        discountlabel.setText("0%");
        PriceList.removeAll();
        ItemList.removeAll();
        CName.setText("");
        CPhNo.setText("");
        repaint();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void FrenchFriesSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchFriesSButtonActionPerformed
        // TODO add your handling code here:                                                 
        // TODO add your handling code here:
        ItemList.add(p);
        PriceList.add("" + (p1));
        total += p1;
        itemcounter++;
        TotalCost.setText("" + total);
        TotalCostLabel.setText("" + total);
        if (discount == 1)
        {
            discountlabel.setText("10%");
            double total1 = total*0.9;
            TotalCostLabel.setText("" + total1);
        }
        repaint();
    }//GEN-LAST:event_FrenchFriesSButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if(orderplaced == 0)
        {
            orderplaced = 1;
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atishaydatabase","","");
            String name1,phno,uidstr,sql;
            name1 = CName.getText();
            phno = CPhNo.getText();
            Statement st1 = con.createStatement();
            String sql1 = "Select uid from contacts;";
            ResultSet rs = st1.executeQuery(sql1);
            int uid = 0;
            while(rs.next())
            {
                uid = Integer.parseInt(rs.getString("uid"));
            }
            uid++;
            uidstr = "" + uid;
            CUID.setText(uidstr);
            sql="insert into contacts values('"+name1+"','"+phno+"','"+uidstr+"')";
            Statement st=con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Contact Saved");
            st.close();
            con.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/atishaydatabase","","");
            String name1,phno,uidstr = "";
            int uid = 0, checker = 0;
            ResultSet rs2 = null;
            name1 = CName.getText();
            phno = CPhNo.getText();
            Statement st2 = con1.createStatement();
            String sql1 = "Select phno from contacts;";
            ResultSet rs = st2.executeQuery(sql1);
            while(rs.next())
            {
                if (phno == rs.getString("phno"));
                {
                    checker = 1;
                    discount = 1;
                    orderplaced = 1;
                }
            }
            if(checker == 1)
            {
                Class.forName("java.sql.DriverManager");
                Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/atishaydatabase","","");
                Statement st3 = con2.createStatement();
                String sql2 = "Select * from contacts where phno ='" + phno + "';";
                rs2 = st3.executeQuery(sql2);
                while(rs2.next())
                {
                    uid = Integer.parseInt(rs2.getString("uid"));
                    name1 = rs2.getString("name");
                }
                CName.setText(name1);
            }
            if(checker == 0)
            {
                JOptionPane.showMessageDialog(null,"Contact not found : ADD contact"); 
            }
            uidstr = "" + uid;
            CUID.setText(uidstr);
            rs.close();
            rs2.close();
            st2.close();
            con1.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in connection" + e);
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BSIcecreamButton;
    private javax.swing.JButton Burger1;
    private javax.swing.JButton Burger2;
    private javax.swing.JButton Burger3;
    private javax.swing.JButton Burger4;
    private javax.swing.JButton Burger5;
    private javax.swing.JButton Burger6;
    private javax.swing.JButton Burger7;
    private javax.swing.JButton Burger8;
    private javax.swing.JLabel BurgerLabel;
    private javax.swing.JButton CIcecreamButton;
    private javax.swing.JTextField CName;
    private javax.swing.JLabel CNameLabel;
    private javax.swing.JTextField CPhNo;
    private javax.swing.JLabel CPhNoLabel;
    private javax.swing.JLabel CUID;
    private javax.swing.JButton CocaColaButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel DiscountL;
    private javax.swing.JLabel DrinkLabel;
    private javax.swing.JButton FrenchFriesLButton;
    private javax.swing.JButton FrenchFriesSButton;
    public java.awt.List ItemList;
    private javax.swing.JLabel MENULabel;
    private javax.swing.JButton MirindaButon;
    private javax.swing.JLabel Order;
    private javax.swing.JButton OrderButton;
    private javax.swing.JLabel OrderNoLAbel;
    private javax.swing.JLabel OthersLabel;
    private javax.swing.JButton PepsiButton;
    private java.awt.List PriceList;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JLabel TotalCost;
    private javax.swing.JLabel TotalCostLabel;
    private javax.swing.JLabel TotalLabela;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel discountlabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sevenUPButton;
    private javax.swing.JLabel uidLabel;
    // End of variables declaration//GEN-END:variables
}
